### PR TITLE
change the returned data from kava and add flag for monitorViewEvents

### PR DESCRIPTION
**Pull request by itaykinnrot**

### CODE REVIEW

**Comment by itaykinnrot** [comment]
Dont merge till @erankor  approve

**Comment by erankor** [comment]
@itaykinnrot, a couple of comments -
1. The code has to support both formats for now, since we can't really make the player+server change together (due to caching). So we need something like - `if (typeof parsedData === 'object') { new code } else { old code }`. 
2. I want the default to be 'enabled', currently if the property is not sent by the server it will be disabled. So either - a. you'll check whether the property exists or b. we'll change the definition to viewEventsDisabled. Let me know what you prefer.
3. The 3 !'s looks a bit redundant :) one would suffice.

**Comment by itaykinnrot** [comment]
fixed @erankor

**Comment by erankor** [comment]
Looks good to me, you can probably simplify the condition to viewEventsEnabled === false, but not really critical...

**Pull request closed without merging**
