### PR TITLE
iPad bumper bug - Added missing condition for iPad/tablet:

### PR DESCRIPTION
**Pull request by mksolemn**
How to test:
go to: http://player.kaltura.com/docs/index.php?path=kvast
open devTools and select iPad;

This will cause bumper to hang and player will remain in frozen state...

Solution:
if( source.getFlavorId() && source.getFlavorId().toLowerCase() == 'iphonenew' || source.getFlavorId().toLowerCase() == 'ipadnew')

Add missing condition. For ipad all flavor sources were getting set from desktop sources NOT mobile sources.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @mksolemn,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by OrenMe** [comment]
Hi @mksolemn, thanks for finding the issue.
ipadNew is a tag indicating higher resolutions/bitrates so it is used for desktop although the name might be a bit off.
Can you add more details about your issue? please note emulators might cause issues and it is better to verify on real device.

**Comment by mksolemn** [comment]
> Hi @mksolemn, thanks for finding the issue.
> ipadNew is a tag indicating higher resolutions/bitrates so it is used for desktop although the name might be a bit off.
> Can you add more details about your issue? please note emulators might cause issues and it is better to verify on real device.

I see your point. The real issue may be deeper in the logic of selected media source, specifically lower bitrate media source - since it's fine with higher bitrate sources.
- go to official demo for bumper:  http://player.kaltura.com/docs/index.php?path=kvast;
- on chrome dev tools select iPad;
- refresh and click play;
- loader image will popup and player will hang.

image

**Comment by OrenMe** [comment]
Hi @mksolemn can you please confirm on a real IPad device

**Comment by OrenMe** [comment]
@mksolemn I'm closing this for now, if you are still able to confirm please reopen.

**Pull request closed without merging**
