### PR TITLE
SUP-7353 removing number of clips from multiple playlist view all but…

### PR DESCRIPTION
**Pull request by omridevk**
… the current playlist

### CODE REVIEW

**Comment by omridevk** [comment]
Since we don't want to do extra API calls to figure out the number of clips, it is best to just not do it at all for all playlists regardless if it is a rule based playlist(where the content is XML and not CSV of entries) or normal playlist.

**Comment by omridevk** [comment]
@OrenMe 
Can you please review (same PR as the other one with a new branch name with the correct JIRA)

**Comment by omridevk** [comment]
I have removed a string attribute:
'mwe-embedplayer-videos'

not sure what will happen for those that uses it and if we should alert them of this change somehow?

**Comment by OrenMe** [comment]
@omridevk please fix conflict with 2.51 so we can merge

**Pull request closed without merging**
