### PR TITLE
Update EmbedPlayer.php

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @paladox,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by kaltura-hooks** [comment]
Hi @paladox,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by paladox** [comment]
Hi I doint really want to include my address.

**Comment by jessp01** [comment]
@paladox, I am sorry but we can only merge requests after users signed the CLA, which requires a legal address. This is a legal requirement and I'm afraid it must be fulfilled. 
If you have specific questions or concerns, please send an email to legal@kaltura.com and community@kaltura.com so we can address them.

**Comment by mdale** [comment]
@paladox maybe you can associate with wikimedia foundation or something like that to fulfill address requrimetns. 

@jessp01 can we turn off the generalized platform build reply for mwEmbed repo?

**Comment by paladox** [comment]
@mdale I doint work for Wikimedia foundation.

**Pull request closed without merging**
