### PR TITLE
Fixing jQuery non-conflict for several use-cases

### PR DESCRIPTION
**Pull request by lelikg**
Fixing the following error in several cases of embedding kWidget

Uncaught TypeError: Cannot read property 'ajax' of undefined

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @lelikg,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by lelikg** [comment]
I signed the CLA, but it's not working for some reason...

**Comment by lelikg** [comment]
@itaykinnrot seems like the CLA check is broken

**Comment by jessp01** [comment]
Github changed their API, our CLA hook now changed accordingly.

**Comment by lelikg** [comment]
@jessp01 awesome, thanks!

**Comment by lelikg** [comment]
@OrenMe can this be merged?

**Comment by lelikg** [comment]
hi guys any chance you gonna merge this? :)

**Comment by OrenMe** [comment]
Thanks @lelikg - merged.

**Pull request merged**
