### PR TITLE
fix(SUP-24727): sanitize playlist name

### PR DESCRIPTION
**Pull request by lianbenjamin**

### CODE REVIEW

**Comment by OrenMe** [comment]
LGTM.
Just make sure you are working against the next version branch v2.87(might need to open it)

**Comment by lianbenjamin** [comment]
> LGTM.
> Just make sure you are working against the next version branch v2.87(might need to open it)

@OrenMe I see that v2.87 is not opened yet, who should I talk to in order to open it?

**Comment by OrenMe** [comment]
it is now opened

**Comment by lianbenjamin** [comment]
> it is now opened

@OrenMe Roi and I did a basic sanity test and it works fine as well against v2.87.

**Pull request merged**
