### PR TITLE
remove legacy live analytics

### PR DESCRIPTION
**Pull request by kalturaguy**

### CODE REVIEW

**Comment by kalturaguy** [comment]
@OrenMe  @erankor   This is not used anymore....

**Comment by OrenMe** [comment]
@kalturaguy @erankor so this is approved for removal?

**Comment by DBezemer** [comment]
@OrenMe this is still used in OnPrem as Kava is not ready for OnPrem yet. Can we keep it in the player for the time being (maybe just disabled by default). Otherwise we're stuck with v2.72 until Kava is released for Onprem

**Comment by kalturaguy** [comment]
@DBezemer  Do you have "legacy" live analytics? Kanalony?

**Pull request merged**
