### PR TITLE
fix(SUP-24104): Auto play ignores bumper

### PR DESCRIPTION
**Pull request by shalommeoded**
Set the vid.volume to 0 if we are on autoPlay

### CODE REVIEW

**Review by OrenMe — COMMENTED** [review]
maybe see if we can take the main player volume instead

**Comment by shalommeoded** [comment]
@OrenMe 
Won't work since for some reason the player volume is still set to 0, however, the vid.volume is still set to 1.

**Comment by OrenMe** [comment]
@shalommeoded but this is exactly what I was referring to - take the volume from player always, don't check autoplay - and I would assume we do the exact check in player as well - so avoid duplicating the logic all around.

**Review by OrenMe — APPROVED** [review]

**Comment by kaltura-hooks** [comment]
Hi @shalommeoded,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Pull request merged**
