### PR TITLE
fix(SUP-12496): ad noticeMessage appears only for preroll

### PR DESCRIPTION
**Pull request by ErezBouskila**
@OrenMe  Please review PR, The noticeMessage only appears for preroll and now it will show for all ads. I confirmed on my end that it works with pre mid and post.

### CODE REVIEW

**Comment by dan-ziv** [comment]
@ErezBouskila 
We are already doing it in `getAdContainer`
Why this is not enough?

**Comment by ErezBouskila** [comment]
@OrenMe @dan-ziv getAdContainer is only called one time, that is way the countdown notice is only showed for the preroll.

**Comment by dan-ziv** [comment]
@ErezBouskila 
So we can remove the call from `getAdContainer`?
Seems its redundant now.

**Comment by ErezBouskila** [comment]
@dan-ziv I will remove it and check

**Comment by ErezBouskila** [comment]
@dan-ziv Removed and it works.

**Pull request merged**
