### PR TITLE
FEC-3683

### PR DESCRIPTION
**Pull request by amirch1**
add and remove rotate class only when changing source / stream and not when enabling / disabling the button. Also fix sourceSwitchingEnd event triggering logic and allow source switching when the player is not playing (for example when the player is loaded and ready).

### CODE REVIEW

**Comment by amirch1** [comment]
@mdale - renamed "rotate" class name to "inProgress" - is this OK?

**Comment by mdale** [comment]
Do we have any other camel case states? We should align naming conventions with existing CSS states: 
http://knowledge.kaltura.com/kaltura-player-toolkit-theme-skin-and-plugins-guide#Player States CSS <http://knowledge.kaltura.com/kaltura-player-toolkit-theme-skin-and-plugins-guide#Player%20States%20CSS>

**Comment by amirch1** [comment]
@mdale  - how does "in-progress-state" sounds?

**Comment by mdale** [comment]
Perfecto ;)

**Pull request merged**
