### PR TITLE
SUP-8636 call getInterface to make sure layout builder exist so we ca…

### PR DESCRIPTION
**Pull request by omridevk**
…n disable hover controls

### CODE REVIEW

**Comment by omridevk** [comment]
@mrkfdr 
Discussed with Itay, he asked someone from application team to review this. 

Let me know what you think.

Thanks.

**Comment by mrkfdr** [comment]
you get the interface but don't perform the check ?

**Comment by omridevk** [comment]
@mrkfdr 
I don't need to check, I am calling getInterface just to make sure that layoutBuilder is actually initialized before we disable the hover components. Maybe I misunderstood you.

**Comment by mrkfdr** [comment]
Ok then

**Comment by omridevk** [comment]
@itaykinnrot , @OrenMe 

Can this be merged please? we want to QA this as soon as possible so it can be moved to Application team for further QA testing. 

Thanks.

**Pull request merged**
