### PR TITLE
KMS-13306 sanitize entry name in thumbnail alt to prevent XSS attacks

### PR DESCRIPTION
**Pull request by muli**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @muli,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by muli** [comment]
@OrenMe - any update? Can this be merged?

**Comment by OrenMe** [comment]
@muli is this still relevant?

**Comment by muli** [comment]
Yes... Without this fix, the player is vulnerable to XSS.

**Pull request merged**
