### PR TITLE
peer5 plugin update

### PR DESCRIPTION
**Pull request by mrbar42**
This is a change needed as part of the integration simplification.

### CODE REVIEW

**Comment by shacharz** [comment]
@itaykinnrot  what base branch should we set for this PR?

**Comment by jessp01** [comment]
@itaykinnrot, @OrenMe, please answer @shacharz's question.

**Comment by OrenMe** [comment]
Hi @shacharz - 2.49 is the next release branch.

**Comment by mrbar42** [comment]
superseded by #3099

**Pull request closed without merging**
