### PR TITLE
OpenX plugin for Kaltura player.

### PR DESCRIPTION
**Pull request by cinar**
Hi Oren, per our discussion, I am sending a PR for the  OpenX plugin for Kaltura player. Looking forward to your feedback. -onur

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @cinar,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by OrenMe** [comment]
Hi @cinar,
Thanks for the PR, would appreciate if you can add a test page, under tests folder, so we can verify the PR is sane.
Kindly please sign the CLA so we can proceed with the PR merging.

**Comment by cinar** [comment]
Hi Oren,  we've signed the CLA, and also I added a test page.  Please let me know if you see any problems with the code.

**Comment by OrenMe** [comment]
@cinar this PR causes the player to crash.
I've refactored the code to align with the new plugin architecture.
You can find the updated code in a branch called openX.
Please include a test page that has a config that shows the plugin load an ad and plays it as well.

Closing this one in the meantime as it's not functional in current form.
Thanks.

**Pull request closed without merging**
