### PR TITLE
FEC-3653: Always update orginalParnetViewPortContent to restore viewport after fs

### PR DESCRIPTION
**Pull request by mdale**

### CODE REVIEW

**Comment by itaykinnrot** [comment]
@mdale please open pulls on version branch
@amirch1 can you please review?

**Comment by mdale** [comment]
@amirch1  did you check this?

**Comment by amirch1** [comment]
@mdale - I thought this was fixed with https://kaltura.atlassian.net/browse/SUP-4129. Seems we missed this. Do we need this to 2.32? If so, can you reopen the pull request on 2.32?

**Comment by mdale** [comment]
can we just merge to master then update?

**Comment by amirch1** [comment]
We can't merge back master to 2.32. I've created a new pull request on 2.32 and merged it. Will be available with v2.32.rc9

**Pull request closed without merging**
